name: Model Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-sugar  # For better test output
    
    - name: List models directory
      run: |
        mkdir -p models
        ls -la models/
      
    - name: Run model tests
      run: |
        python -m pytest test_model.py -v --capture=no